set(MESSAGING_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/eventmessage.h
        ${CMAKE_CURRENT_LIST_DIR}/eventmessage.cpp
        ${CMAKE_CURRENT_LIST_DIR}/querymessage.h
        ${CMAKE_CURRENT_LIST_DIR}/querymessage.cpp
        ${CMAKE_CURRENT_LIST_DIR}/specializedmessages.h
        ${CMAKE_CURRENT_LIST_DIR}/specializedmessages.cpp
        ${CMAKE_CURRENT_LIST_DIR}/messagemanager.h
        ${CMAKE_CURRENT_LIST_DIR}/messagemanager.cpp
)
