get_filename_component(SERVERBRIGE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SERVERBRIGE_SRC_DIR "${SERVERBRIGE_ROOT}/src")
set(SERVERBRIGE_TESTS_DIR "${SERVERBRIGE_ROOT}/tests")

file(GLOB_RECURSE SERVERBRIGE_SOURCES CONFIGURE_DEPENDS
    "${SERVERBRIGE_SRC_DIR}/*.cpp"
    "${SERVERBRIGE_SRC_DIR}/*.h"
    "${SERVERBRIGE_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE SERVERBRIGE_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${SERVERBRIGE_SRC_DIR}/*.cpp"
)
list(FILTER SERVERBRIGE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER SERVERBRIGE_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

